table Customers
	lineageTag: bbbc1988-70f7-4035-ba25-638058ddd07e
	sourceLineageTag: e8f37b41-5f21-41c7-862c-b05ff860a907

	measure 'Customer Rentention Rate %' = EXTERNALMEASURE("Customer Rentention Rate %", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Customer Metrics
		lineageTag: 04416807-cef3-4bc3-b75d-b5463d6237b1
		sourceLineageTag: 30d053a3-37ab-4db0-932c-33775d54ac14
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Top Customer Segment' = EXTERNALMEASURE("Top Customer Segment", STRING, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Customer Metrics
		lineageTag: 16c1a95b-7f82-4d5c-b3d4-d7cb0f915c9b
		sourceLineageTag: dfb8217e-71e6-4fe6-ae20-d8c5b2ec263b
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isText":true}

	measure 'Total Customers' = EXTERNALMEASURE("Total Customers", INTEGER, "DirectQuery to AS - SM_SupplyChain")
		formatString: 0
		displayFolder: Customer Metrics
		lineageTag: e790523d-cc6f-433e-96d0-f9b2394a6c8c
		sourceLineageTag: 42ba1ed2-0e7a-4444-b9fc-316b7a837981
		dataCategory: Uncategorized

	column 'Customer ID'
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: d2ffc702-1cf3-4de4-b8bc-dffcf4febae2
		sourceLineageTag: 7e9021f8-18f2-4cce-951a-1dfd0b620edb
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = User

	column 'First Name'
		dataType: string
		displayFolder: Customer Details
		lineageTag: acc4f7d2-396d-4b76-827a-14bd81134e6f
		sourceLineageTag: c76c550d-bc6b-489a-8cd3-f69da81c7bd1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = User

	column 'Last Name'
		dataType: string
		displayFolder: Customer Details
		lineageTag: 4eb19309-3e46-4850-b14d-11b6b0e76d88
		sourceLineageTag: e3f9a65c-c3eb-4890-9c40-b8396595a2a4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Last Name

		annotation SummarizationSetBy = User

	column State
		dataType: string
		lineageTag: 65f71376-4fa1-4d33-ae62-577a0179d8a7
		sourceLineageTag: 27c60933-d791-40b0-bd8d-9d15c60a4109
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = User

	column Country
		dataType: string
		lineageTag: 3097dc11-6132-4057-8904-c9e9fa96665c
		sourceLineageTag: 62398a00-ca32-4210-909f-350b1b032422
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = User

	column Segment
		dataType: string
		lineageTag: 31e94cfe-6d1d-4b39-8876-bd1e2d2a3d46
		sourceLineageTag: 4b853bdc-a6f0-4bc0-b879-9877fa476dd9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = User

	column 'Unique Customer Key'
		dataType: string
		displayFolder: Customer Details
		lineageTag: 5f76db44-a8a6-434e-b13f-0b7e09c881bd
		sourceLineageTag: 067f2b27-76e8-42b4-98bb-903aedfea8ef
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Unique Customer Key

		annotation SummarizationSetBy = User

	hierarchy 'Customer Geography Hierarchy'
		lineageTag: b49b6d45-d690-4d6d-ab34-96652edeba8c
		sourceLineageTag: 2ac8f48e-d050-4e09-bbaf-0761f261af06

		level Country
			lineageTag: e6b9bdea-3285-4249-b476-a33503c6945f
			sourceLineageTag: e3c62e75-3c81-4209-90ee-1dd23d816791
			column: Country

		level State
			lineageTag: 2e3128f6-15d8-4b50-89ea-7d9b11f96542
			sourceLineageTag: 5c533ee5-58d6-4ff7-90ef-ed36f56ef8b2
			column: State

	partition Customers = entity
		mode: directQuery
		source
			entityName: Customers
			expressionSource: 'DirectQuery to AS - SM_SupplyChain'

