table Orders
	lineageTag: 702edbb5-f5bb-485f-af1b-e4737765bb17
	sourceLineageTag: d23aa252-be1e-44b1-8392-bcc62e551ffa

	measure 'Average Discount' = EXTERNALMEASURE("Average Discount", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Order Metrics
		lineageTag: 7c3a3686-cfa8-441d-8f7b-96bfa78d681b
		sourceLineageTag: 24cc3ab1-ef01-4586-89d2-18c4a9535845
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Order Value' = EXTERNALMEASURE("Average Order Value", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Order Metrics
		lineageTag: 902b9496-f0a1-4698-bd84-6acc25b981a3
		sourceLineageTag: a7b080f3-f74a-45a9-9e76-27dfe8584030
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Price' = EXTERNALMEASURE("Average Price", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Order Metrics
		lineageTag: 1e026fec-59a8-4c27-a69f-ecebd1944e7b
		sourceLineageTag: 161bec54-c7ab-4298-824d-5b25ebb55eed
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Discount Effectiveness Rate %' = EXTERNALMEASURE("Discount Effectiveness Rate %", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Order Metrics
		lineageTag: e997a721-e8b2-4449-9062-cc187f24a5dd
		sourceLineageTag: 2c3d3454-14a6-44b1-8d97-d4f631c66d9f
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Discount Rate %' = EXTERNALMEASURE("Discount Rate %", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Order Metrics
		lineageTag: 55b56a32-ad8c-4ab6-aaec-4daa50553cea
		sourceLineageTag: 6f9f6841-63f8-4ab7-a56f-51c625320866
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Margin %' = EXTERNALMEASURE("Profit Margin %", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Order Metrics
		lineageTag: c38c7170-0c70-48f8-bf8c-ac7cc379d2a7
		sourceLineageTag: 9398e6f8-b381-476d-9627-9bc847f305ab
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Discounts' = EXTERNALMEASURE("Total Discounts", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Order Metrics
		lineageTag: 1870a553-e3eb-4f84-bcd5-56dcc16f341f
		sourceLineageTag: ba0d6f87-a6b0-4d29-b946-391b24fa820c
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders' = EXTERNALMEASURE("Total Orders", INTEGER, "DirectQuery to AS - SM_SupplyChain")
		formatString: 0
		displayFolder: Order Metrics
		lineageTag: d9357f05-2251-4507-b29b-d5d58ae29002
		sourceLineageTag: 277dc976-8ca6-4f14-91d2-e80eeeee0574
		dataCategory: Uncategorized

	measure 'Total Products Sold' = EXTERNALMEASURE("Total Products Sold", INTEGER, "DirectQuery to AS - SM_SupplyChain")
		formatString: 0
		displayFolder: Order Metrics
		lineageTag: bb4a8109-af02-41ec-aac9-67ecd99d8cbb
		sourceLineageTag: dd8fd45b-0ad8-482c-8a3c-a23ad429b980
		dataCategory: Uncategorized

	measure 'Total Profit' = EXTERNALMEASURE("Total Profit", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Order Metrics
		lineageTag: 587ee570-9375-4aae-8aad-5025d2c26f30
		sourceLineageTag: f1a2dda2-46fc-4980-bf06-ac9c306c3e85
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales' = EXTERNALMEASURE("Total Sales", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Order Metrics
		lineageTag: 18a0c912-579e-4c86-9fe4-d66d5feb7ee2
		sourceLineageTag: 1b49f8aa-5067-4eba-8554-aafb0bc16ff8
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales After Discount' = EXTERNALMEASURE("Total Sales After Discount", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Order Metrics
		lineageTag: 8232fc81-69f2-4158-b7d2-a0ca7f40087e
		sourceLineageTag: 9e0d799f-d165-47a7-94d8-b35645c9c909
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Fulfillment Time' = EXTERNALMEASURE("Average Fulfillment Time", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Shipping Metrics
		lineageTag: 41ec518d-39d3-4cc1-b944-ed8053418d39
		sourceLineageTag: 5a577cd1-ca02-4a20-a86f-c2aebe51e15e
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Lead Time' = EXTERNALMEASURE("Average Lead Time", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Shipping Metrics
		lineageTag: fe130a86-23a3-475f-bee7-1df2cd3f4e11
		sourceLineageTag: 04820bed-7c3c-4295-bdc1-b8b1a42021f1
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Shipping Time' = EXTERNALMEASURE("Average Shipping Time", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Shipping Metrics
		lineageTag: 75111fd8-8f59-49ad-b43c-da080ad07cf3
		sourceLineageTag: b885e702-2a1d-49d7-9684-6cfd881c407a
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Late Delivery Count' = EXTERNALMEASURE("Late Delivery Count", INTEGER, "DirectQuery to AS - SM_SupplyChain")
		formatString: 0
		displayFolder: Shipping Metrics
		lineageTag: 825b7dd4-42be-4979-92ce-71820d809d6f
		sourceLineageTag: 5fb7f46b-25fd-479b-bdd3-4754f6ce18dd
		dataCategory: Uncategorized

	measure 'Late Delivery Rate %' = EXTERNALMEASURE("Late Delivery Rate %", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Shipping Metrics
		lineageTag: 07238004-d5c0-47a0-b8e4-57ba14cb9788
		sourceLineageTag: 12ca9cde-be75-47fa-b73c-4683de3898f7
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'On Time Delivery Count' = EXTERNALMEASURE("On Time Delivery Count", INTEGER, "DirectQuery to AS - SM_SupplyChain")
		formatString: 0
		displayFolder: Shipping Metrics
		lineageTag: dc2c0377-bcbb-4abb-b3eb-733fb7912879
		sourceLineageTag: 228bd2db-4d3e-4fcf-a332-a9d5c0c8d5e5
		dataCategory: Uncategorized

	measure 'On Time Delivery Rate %' = EXTERNALMEASURE("On Time Delivery Rate %", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Shipping Metrics
		lineageTag: 1ce73b35-baac-4b33-ad79-73bb89438cf7
		sourceLineageTag: aab4aa75-b0b8-4aa1-8e72-3ba1c8e32a10
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Target = EXTERNALMEASURE("Target", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Shipping Metrics
		lineageTag: 375dde7d-57f4-4d43-9c5b-089d6d5c649f
		sourceLineageTag: a0cab19a-032c-495d-8638-179bd37c1bc7
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LY Sales' = EXTERNALMEASURE("LY Sales", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Time Intelligence
		lineageTag: 0e251d7c-8579-4ccc-b5ef-de34cb0e3ed6
		sourceLineageTag: a10a6c7b-74e6-45ff-91e5-d2fd9cd77ff6
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MTD Sales' = EXTERNALMEASURE("MTD Sales", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Time Intelligence
		lineageTag: 6e15c7da-50a7-4af5-9d37-945d4409566e
		sourceLineageTag: 71b1a503-19da-4992-a82f-4403ab3785a5
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Sales' = EXTERNALMEASURE("QTD Sales", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Time Intelligence
		lineageTag: d71b23ee-6aa3-4895-a562-7b68d22ad396
		sourceLineageTag: 59670388-fead-4612-95e4-32af66910603
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY Sales Change' = EXTERNALMEASURE("YoY Sales Change", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Time Intelligence
		lineageTag: 9ad01aae-af38-4a44-9f26-e6f765d40dec
		sourceLineageTag: c22368f1-5651-48ca-b1ad-1c7a7e931f56
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY Sales Growth %' = EXTERNALMEASURE("YoY Sales Growth %", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Time Intelligence
		lineageTag: acefcdc1-90f8-4b72-b4a9-6c3aa31c1d2a
		sourceLineageTag: 13088931-1bec-41c8-ab7b-05f1e1183381
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Sales' = EXTERNALMEASURE("YTD Sales", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Time Intelligence
		lineageTag: affa7d80-6b9b-46f5-b707-0a38b262a276
		sourceLineageTag: 03bd4a2a-f340-48de-bbd0-551fa675e346
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 992bdcff-07fd-4700-91f1-e459a488f34c
		sourceLineageTag: 79df6d07-3dae-4968-a8a6-f8ae3ac008ab
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: Order ID

		annotation SummarizationSetBy = User

	column 'Order Date'
		dataType: dateTime
		formatString: Short Date
		displayFolder: Date Keys
		lineageTag: 30812e00-9409-4551-86a9-255952fc71c3
		sourceLineageTag: 2b9e0e8a-985a-40ea-986f-7b9fce397f19
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = User

	column 'Customer ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0bde44c5-11c9-4859-b2ad-33b27208a26c
		sourceLineageTag: 327b5a6e-fd98-48fa-9c00-610ffd6a77c0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = User

	column 'Product ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 31a5ac83-d4e6-4988-b3fc-908a5d9ff22b
		sourceLineageTag: 40a6a491-b577-4f43-bd71-043909438efd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = User

	column 'Country ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 910b9acf-3713-4733-b256-93903512fc71
		sourceLineageTag: a16f5740-9313-4860-81a8-e4bfb5b266ae
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Country ID

		annotation SummarizationSetBy = User

	column Discount
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Order Metrics
		lineageTag: 84949d97-81e6-4994-b58a-11693c04afbc
		sourceLineageTag: e6a2775d-97df-4fd5-9077-8308d3bd29c3
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = User

	column Price
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Order Metrics
		lineageTag: 3a9bed1d-be79-4e2a-9557-739876c2f406
		sourceLineageTag: f6ee4243-13ea-4cd4-a796-7b030877f23e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = User

	column Quantity
		dataType: int64
		formatString: 0
		displayFolder: Order Metrics
		lineageTag: 08dfc697-fc9b-402b-8915-73a66c223d35
		sourceLineageTag: 431dfe97-0371-4dcf-8b60-49715cd35c5a
		dataCategory: Uncategorized
		summarizeBy: average
		sourceColumn: Quantity

		annotation SummarizationSetBy = User

	column Total
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Order Metrics
		lineageTag: 628f1d99-ed92-4e99-b451-e7adcd234c4a
		sourceLineageTag: 1838a936-2b56-4770-9f5d-4398b4a31131
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = User

	column 'Total After Discount'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Order Metrics
		lineageTag: 3a2b89d6-5939-439a-974a-47d25add18fb
		sourceLineageTag: e1e09d1e-a49f-4eac-ba2a-96f206dcfaa9
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Total After Discount

		annotation SummarizationSetBy = User

	column Profit
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Order Metrics
		lineageTag: 156db776-89db-4036-b23b-691590f2cd19
		sourceLineageTag: 00a067d8-fad9-4930-82bd-10f948b47274
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = User

	column 'Payment Type'
		dataType: string
		lineageTag: 10de583b-06e7-4d88-9f4f-15cb39cf4cf1
		sourceLineageTag: 67c4668b-3fa6-4bca-9aff-e60ded46227f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Payment Type

		annotation SummarizationSetBy = User

	column 'Days For Shipping'
		dataType: int64
		formatString: 0
		displayFolder: Shipping Details
		lineageTag: 05fd3648-cddf-46e5-9699-ff7702329ebc
		sourceLineageTag: db2b87fc-7cb3-471e-bde2-b179e04697da
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Days For Shipping

		annotation SummarizationSetBy = User

	column 'Days For Shipment'
		dataType: int64
		formatString: 0
		displayFolder: Shipping Details
		lineageTag: edc1c132-8958-477c-937f-dffc1cae6624
		sourceLineageTag: 69a31723-e10b-432f-ba33-15e7617c5069
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Days For Shipment

		annotation SummarizationSetBy = User

	column 'Shipping Mode'
		dataType: string
		displayFolder: Shipping Details
		lineageTag: cbcf406f-c38e-4ce6-94d8-e2c40b556ec7
		sourceLineageTag: 69e27193-808d-454b-bf26-963b080baab7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Shipping Mode

		annotation SummarizationSetBy = User

	column 'Late Delivery Risk'
		dataType: int64
		formatString: 0
		displayFolder: Shipping Details
		lineageTag: 01356d75-f684-4cda-b7e0-cfab09f253bf
		sourceLineageTag: 3541c319-b4b2-462a-a415-ad2e02d3c769
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Late Delivery Risk

		annotation SummarizationSetBy = User

	column 'Delivery Status'
		dataType: string
		displayFolder: Shipping Details
		lineageTag: cd7baffa-2874-40e5-905a-65cd1b5407a0
		sourceLineageTag: 3740a1d4-5f79-4053-afd7-eb20bbd201f3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Delivery Status

		annotation SummarizationSetBy = User

	column 'Shipping Date'
		dataType: dateTime
		formatString: Short Date
		displayFolder: Date Keys
		lineageTag: 30ee0385-f9fa-4f56-b0d3-aa013f985b58
		sourceLineageTag: 4c7c51c1-385c-449b-ab9e-29caf1d4a060
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Shipping Date

		annotation SummarizationSetBy = User

	column 'On Time Shipping Target'
		dataType: double
		displayFolder: Shipping Metrics
		lineageTag: f337f50a-4082-4f49-9ea2-abb174b94004
		sourceLineageTag: ae691b35-85a3-4b31-b354-0b21fe9ed0af
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: On Time Shipping Target

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = entity
		mode: directQuery
		source
			entityName: Orders
			expressionSource: 'DirectQuery to AS - SM_SupplyChain'

