table Products
	lineageTag: dbabd01a-9bfb-49e7-986c-de139f187f08
	sourceLineageTag: 88423e5f-2249-478d-9119-192ba6dee359

	measure 'Average Product Price' = EXTERNALMEASURE("Average Product Price", DOUBLE, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Product Metrics
		lineageTag: 89aa97ea-ea2b-4a6b-8215-ca52e5c7db81
		sourceLineageTag: b1a02d0a-7495-48fb-9653-6806773df34b
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Top Selling Product' = EXTERNALMEASURE("Top Selling Product", STRING, "DirectQuery to AS - SM_SupplyChain")
		displayFolder: Product Metrics
		lineageTag: 225e24b0-6cd5-4c00-aad9-c8298b503204
		sourceLineageTag: 579b254c-a667-4454-8f50-c55a60885a17
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isText":true}

	column 'Product ID'
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 2d0bd49f-f99c-432e-908e-9afc91ed74fb
		sourceLineageTag: 10fdaac9-0270-4df1-93dd-9e8125134197
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = User

	column Product
		dataType: string
		displayFolder: Product Details
		lineageTag: 6d6a575d-9b6e-42ca-a0cf-9239ad48829d
		sourceLineageTag: b842c6e6-f338-42ad-911c-1273da256b70
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = User

	column 'Category ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c2ed28f2-2c0a-4c3b-bfd0-ef7d3e4a08c3
		sourceLineageTag: 7175ed37-4bde-4858-9822-a7b3c48530c6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Category ID

		annotation SummarizationSetBy = User

	column 'Department ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c5743cbb-01d8-4949-b61f-8b858bd9eaea
		sourceLineageTag: 241ee521-e6d8-4793-a03e-56e24a175660
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Department ID

		annotation SummarizationSetBy = User

	column Price
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Product Details
		lineageTag: cfafe167-cd07-4cd3-8ef8-bfcaf6acde1c
		sourceLineageTag: be4d1e2e-2b9e-41e6-9d49-632138beb024
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = User

	partition Products = entity
		mode: directQuery
		source
			entityName: Products
			expressionSource: 'DirectQuery to AS - SM_SupplyChain'

